/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Producto;
import models.ProductoCon;
import java.util.logging.Level;
import java.util.logging.Logger;
import models.Venta;
import models.VentaCon;

/**
 *
 * @author JOHAN VARON
 */
public class Registro_Ventas extends javax.swing.JFrame {
    
    Producto p = new Producto();
    ProductoCon product = new ProductoCon();
    Venta v = new Venta();
    VentaCon vent = new VentaCon();
    DefaultTableModel modelo = new DefaultTableModel();
    int item;
    double TotalPagar = 0.00;
    double ganancia_Total = 0.00;
    

    /**
     * Creates new form Registro_Ventas
     */
    public Registro_Ventas() {
        initComponents();
    }
    
    public void ListarProducto()
    {
        List<Producto> ListarP = product.ListarProductos();
        modelo = (DefaultTableModel) jTableProducto.getModel();
        Object[] ob = new Object[6];
        for (int i = 0; i < ListarP.size(); i++) 
        {
            ob[0] = ListarP.get(i).getTipo();
            ob[1] = ListarP.get(i).getCodigo();
            ob[2] = ListarP.get(i).getNombre();
            ob[3] = ListarP.get(i).getValorUnitario();
            ob[4] = ListarP.get(i).getCantidadBodega();
            ob[5] = ListarP.get(i).getCantidadMinima();
            modelo.addRow(ob);
        }
        jTableProducto.setModel(modelo);
    }

    public void ListarProductoPedidos()
    {
        List<Producto> ListarP = product.ListarProductos();
        modelo = (DefaultTableModel) jTablePedidos.getModel();
        Object[] ob = new Object[5];
        for (int i = 0; i < ListarP.size(); i++) 
        {
            
            ob[0] = ListarP.get(i).getCodigo();
            ob[1] = ListarP.get(i).getTipo();
            ob[2] = ListarP.get(i).getNombre();
            ob[3] = ListarP.get(i).getCantidadBodega();
            ob[4] = ListarP.get(i).getCantidadMinima();
            modelo.addRow(ob);
        }
        jTableProducto.setModel(modelo);
    }
    
    public void ListarVentas()
    {
        List<Venta> ListarV = vent.ListarVentas();
        modelo = (DefaultTableModel) jTableVentas_Estadisticas.getModel();
        Object[] ob = new Object[6];
        for (int i = 0; i < ListarV.size(); i++) 
        {
            ob[0] = ListarV.get(i).getCodigo();
            ob[1] = ListarV.get(i).getDescripcion();
            ob[2] = ListarV.get(i).getCantidad();
            ob[3] = ListarV.get(i).getV_Unitario();
            ob[4] = ListarV.get(i).getIVA();
            ob[5] = ListarV.get(i).getV_Total();
            modelo.addRow(ob);
        }
        jTableProducto.setModel(modelo);
    }
    
    public void LimpiarTabla()
    {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i-1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHeader = new javax.swing.JLabel();
        jPanelNavbar = new javax.swing.JPanel();
        Productos_button = new javax.swing.JButton();
        Realizar_Venta_button = new javax.swing.JButton();
        Estadisticas_button = new javax.swing.JButton();
        Pedidos_button = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabelTipo = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        jTextFieldCantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jLabelMinimo = new javax.swing.JLabel();
        jTextFieldMinimo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProducto = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldVentas_Codigo = new javax.swing.JTextField();
        jTextFieldVentas_Tipo = new javax.swing.JTextField();
        jTextFieldVentas_Nombre = new javax.swing.JTextField();
        jTextFieldVentas_Precio = new javax.swing.JTextField();
        jTextFieldVentas_Stock = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldVenta_Cantidad = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableVentas = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabelTotal_Pago = new javax.swing.JLabel();
        jButtonRegistrar_Venta = new javax.swing.JButton();
        jButtonEliminar_Venta = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButtonPromedio_Ventas = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableVentas_Estadisticas = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabelCodigo_Pedidos = new javax.swing.JLabel();
        jTextFieldCodigo_Pedidos = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldCantidad_Pedido = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldDescripcion_Pedido = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePedidos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelHeader.setIcon(new javax.swing.ImageIcon("C:\\Users\\JOHAN VARON\\Documents\\NetBeansProjects\\Inventario_Tienda\\src\\main\\java\\imagenes\\Imagen1.jpg")); // NOI18N

        jPanelNavbar.setBackground(new java.awt.Color(255, 204, 102));

        Productos_button.setBackground(new java.awt.Color(255, 255, 153));
        Productos_button.setIcon(new javax.swing.ImageIcon("C:\\Users\\JOHAN VARON\\Documents\\NetBeansProjects\\Inventario_Tienda\\src\\main\\java\\imagenes\\descarga.png")); // NOI18N
        Productos_button.setText("Productos");
        Productos_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Productos_buttonActionPerformed(evt);
            }
        });

        Realizar_Venta_button.setBackground(new java.awt.Color(255, 255, 153));
        Realizar_Venta_button.setIcon(new javax.swing.ImageIcon("C:\\Users\\JOHAN VARON\\Documents\\NetBeansProjects\\Inventario_Tienda\\src\\main\\java\\imagenes\\6633320 (1).png")); // NOI18N
        Realizar_Venta_button.setText("Realizar venta");
        Realizar_Venta_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Realizar_Venta_buttonActionPerformed(evt);
            }
        });

        Estadisticas_button.setBackground(new java.awt.Color(255, 255, 153));
        Estadisticas_button.setIcon(new javax.swing.ImageIcon("C:\\Users\\JOHAN VARON\\Documents\\NetBeansProjects\\Inventario_Tienda\\src\\main\\java\\imagenes\\2155722.png")); // NOI18N
        Estadisticas_button.setText("Estadisticas");
        Estadisticas_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Estadisticas_buttonActionPerformed(evt);
            }
        });

        Pedidos_button.setBackground(new java.awt.Color(255, 255, 153));
        Pedidos_button.setIcon(new javax.swing.ImageIcon("C:\\Users\\JOHAN VARON\\Documents\\NetBeansProjects\\Inventario_Tienda\\src\\main\\java\\imagenes\\6384868.png")); // NOI18N
        Pedidos_button.setText("Pedidos");
        Pedidos_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pedidos_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNavbarLayout = new javax.swing.GroupLayout(jPanelNavbar);
        jPanelNavbar.setLayout(jPanelNavbarLayout);
        jPanelNavbarLayout.setHorizontalGroup(
            jPanelNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNavbarLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(Productos_button)
                .addGap(18, 18, 18)
                .addComponent(Realizar_Venta_button)
                .addGap(18, 18, 18)
                .addComponent(Estadisticas_button)
                .addGap(18, 18, 18)
                .addComponent(Pedidos_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelNavbarLayout.setVerticalGroup(
            jPanelNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNavbarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Realizar_Venta_button)
                    .addComponent(Productos_button)
                    .addComponent(Estadisticas_button)
                    .addComponent(Pedidos_button))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));

        jLabel1.setText("Codigo");

        jLabel2.setText("Nombre");

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PAPELERIA", "SUPERMERCADO", "DROGUERIA" }));
        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoActionPerformed(evt);
            }
        });

        jLabelTipo.setText("Tipo");

        jLabelCantidad.setText("Cantidad");

        jLabel3.setText("Precio");

        jButtonRegistrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\JOHAN VARON\\Documents\\NetBeansProjects\\Inventario_Tienda\\src\\main\\java\\imagenes\\359316.png")); // NOI18N
        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        jButtonEliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\JOHAN VARON\\Documents\\NetBeansProjects\\Inventario_Tienda\\src\\main\\java\\imagenes\\3221897.png")); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jLabelMinimo.setText("Minimo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRegistrar))
                .addGap(55, 55, 55))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabelTipo)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxTipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCantidad)
                            .addComponent(jLabel3)
                            .addComponent(jLabelMinimo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldMinimo)
                            .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTipo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCantidad))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMinimo)
                    .addComponent(jTextFieldMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jButtonRegistrar)
                .addGap(18, 18, 18)
                .addComponent(jButtonEliminar)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTableProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Codigo", "Nombre", "Precio", "Cantidad", "Minimo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProducto);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", jPanel2);

        jPanel6.setBackground(new java.awt.Color(255, 204, 102));

        jLabel4.setText("Codigo");

        jLabel5.setText("Tipo");

        jLabel6.setText("Nombre");

        jLabel7.setText("Precio");

        jLabel8.setText("Stock");

        jTextFieldVentas_Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVentas_CodigoActionPerformed(evt);
            }
        });
        jTextFieldVentas_Codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldVentas_CodigoKeyPressed(evt);
            }
        });

        jLabel9.setText("Cantidad");

        jTextFieldVenta_Cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldVenta_CantidadKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jTextFieldVentas_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldVentas_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jTextFieldVentas_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(jTextFieldVentas_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel4)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(98, 98, 98)
                        .addComponent(jLabel7)
                        .addGap(61, 61, 61)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldVenta_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jTextFieldVentas_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldVentas_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldVentas_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldVentas_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldVentas_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldVentas_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldVenta_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTableVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion", "Cantidad", "V_Unitario", "IVA", "V_Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableVentas);

        jPanel7.setBackground(new java.awt.Color(255, 204, 102));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\JOHAN VARON\\Documents\\NetBeansProjects\\Inventario_Tienda\\src\\main\\java\\imagenes\\4564998.png")); // NOI18N
        jLabel10.setText("Total a Pagar : ");

        jLabelTotal_Pago.setText("-----------------------");

        jButtonRegistrar_Venta.setIcon(new javax.swing.ImageIcon("C:\\Users\\JOHAN VARON\\Documents\\NetBeansProjects\\Inventario_Tienda\\src\\main\\java\\imagenes\\359316.png")); // NOI18N
        jButtonRegistrar_Venta.setText("Registrar");
        jButtonRegistrar_Venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrar_VentaActionPerformed(evt);
            }
        });

        jButtonEliminar_Venta.setIcon(new javax.swing.ImageIcon("C:\\Users\\JOHAN VARON\\Documents\\NetBeansProjects\\Inventario_Tienda\\src\\main\\java\\imagenes\\3221897.png")); // NOI18N
        jButtonEliminar_Venta.setText("Eliminar");
        jButtonEliminar_Venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminar_VentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jButtonRegistrar_Venta)
                .addGap(39, 39, 39)
                .addComponent(jButtonEliminar_Venta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabelTotal_Pago, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabelTotal_Pago, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRegistrar_Venta)
                    .addComponent(jButtonEliminar_Venta))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("", jPanel3);

        jPanel8.setBackground(new java.awt.Color(255, 204, 102));

        jButton2.setBackground(new java.awt.Color(255, 255, 153));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\JOHAN VARON\\Documents\\NetBeansProjects\\Inventario_Tienda\\src\\main\\java\\imagenes\\5352365.png")); // NOI18N
        jButton2.setText("Ganancias Totales");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonPromedio_Ventas.setBackground(new java.awt.Color(255, 255, 153));
        jButtonPromedio_Ventas.setIcon(new javax.swing.ImageIcon("C:\\Users\\JOHAN VARON\\Documents\\NetBeansProjects\\Inventario_Tienda\\src\\main\\java\\imagenes\\5360536.png")); // NOI18N
        jButtonPromedio_Ventas.setText("Promedio Ventas");
        jButtonPromedio_Ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPromedio_VentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPromedio_Ventas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jButton2)
                .addGap(36, 36, 36)
                .addComponent(jButtonPromedio_Ventas)
                .addContainerGap(215, Short.MAX_VALUE))
        );

        jTableVentas_Estadisticas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion", "Cantidad", "V_Unitario", "IVA", "V_Total"
            }
        ));
        jScrollPane4.setViewportView(jTableVentas_Estadisticas);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", jPanel4);

        jPanel9.setBackground(new java.awt.Color(255, 204, 102));

        jLabelCodigo_Pedidos.setText("Codigo de producto");

        jTextFieldCodigo_Pedidos.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldCodigo_Pedidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCodigo_PedidosKeyPressed(evt);
            }
        });

        jLabel11.setText("Cantidad pedido");

        jTextFieldCantidad_Pedido.setBackground(new java.awt.Color(255, 255, 204));

        jButton1.setBackground(new java.awt.Color(255, 255, 153));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\JOHAN VARON\\Documents\\NetBeansProjects\\Inventario_Tienda\\src\\main\\java\\imagenes\\6384868.png")); // NOI18N
        jButton1.setText("Realizar Pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Descripcion");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabelCodigo_Pedidos))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jTextFieldCodigo_Pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel11))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldDescripcion_Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jTextFieldCantidad_Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(80, 80, 80)
                .addComponent(jButton1)
                .addGap(89, 89, 89))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelCodigo_Pedidos)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCodigo_Pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCantidad_Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDescripcion_Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTablePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Tipo", "Descripcion", "Stock", "Stock_Minimo"
            }
        ));
        jScrollPane2.setViewportView(jTablePedidos);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        jTabbedPane1.addTab("", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanelNavbar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelHeader, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelNavbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Estadisticas_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Estadisticas_buttonActionPerformed
        // TODO add your handling code here:
        LimpiarTabla();
        ListarVentas();
        GananciaTotal();
        jTabbedPane1.setSelectedIndex(2);        
    }//GEN-LAST:event_Estadisticas_buttonActionPerformed

    private void Realizar_Venta_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Realizar_Venta_buttonActionPerformed
        // TODO add your handling code here:
        LimpiarTabla();
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_Realizar_Venta_buttonActionPerformed

    private void Pedidos_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pedidos_buttonActionPerformed
        // TODO add your handling code here:
        LimpiarTabla();
        jTablePedidos.removeAll();
        ListarProductoPedidos();
        jTabbedPane1.setSelectedIndex(3);
        EsNecesarioHacerPedido();
        
    }//GEN-LAST:event_Pedidos_buttonActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed

        if (!"".equals(jTextFieldID.getText()) || !"".equals(jTextFieldNombre.getText()) || !"".equals(jTextFieldPrecio.getText()) || !"".equals(jTextFieldCantidad.getText()) || !"".equals(jTextFieldMinimo.getText()))
        {
            p.setTipo(jComboBoxTipo.getSelectedItem().toString());
            p.setCodigo(Integer.parseInt(jTextFieldID.getText()));
            p.setNombre(jTextFieldNombre.getText());
            p.setValorUnitario(Double.parseDouble(jTextFieldPrecio.getText()));
            p.setCantidadBodega(Integer.parseInt(jTextFieldCantidad.getText()));
            p.setCantidadMinima(Integer.parseInt(jTextFieldMinimo.getText()));
            product.RegistrarProducto(p);
            LimpiarTabla();
            ListarProducto();
            LimpiarProducto();
            JOptionPane.showMessageDialog(null, "Producto Registrado");
        }
        else{
            JOptionPane.showMessageDialog(null, "Los campos estan vacios");
        }
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void Productos_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Productos_buttonActionPerformed
        // TODO add your handling code here:
        LimpiarTabla();
        ListarProducto();
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_Productos_buttonActionPerformed

    private void jTableProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductoMouseClicked
        // TODO add your handling code here:
        int fila = jTableProducto.rowAtPoint(evt.getPoint());
        jComboBoxTipo.setSelectedItem(jTableProducto.getValueAt(fila, 0).toString());
        jTextFieldID.setText(jTableProducto.getValueAt(fila, 1).toString());
        jTextFieldNombre.setText(jTableProducto.getValueAt(fila, 2).toString());
        jTextFieldPrecio.setText(jTableProducto.getValueAt(fila, 3).toString());
        jTextFieldCantidad.setText(jTableProducto.getValueAt(fila, 4).toString());
        jTextFieldMinimo.setText(jTableProducto.getValueAt(fila, 5).toString());
    }//GEN-LAST:event_jTableProductoMouseClicked

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        if(!"".equals(jTextFieldID.getText()))
        {
            int pregunta = JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar este registro?");
            if (pregunta == 0) {
                int codigo = Integer.parseInt(jTextFieldID.getText());
                product.EliminarProducto(codigo);
                LimpiarTabla();
                ListarProducto();
                LimpiarProducto();
            }
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jTextFieldVentas_CodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldVentas_CodigoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!"".equals(jTextFieldVentas_Codigo.getText())) {
                int Cod = Integer.parseInt(jTextFieldVentas_Codigo.getText());
                p = product.BuscarProductos(Cod);
                if (p.getNombre() != null) {
                    jTextFieldVentas_Tipo.setText(""+p.getTipo());
                    jTextFieldVentas_Nombre.setText(""+p.getNombre());
                    jTextFieldVentas_Precio.setText(""+p.getValorUnitario());
                    jTextFieldVentas_Stock.setText(""+p.getCantidadBodega());
                    jTextFieldVenta_Cantidad.requestFocus();
                }
                else{
                    LimpiarVenta();
                    jTextFieldVentas_Codigo.requestFocus();
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Ingrese el codigo del producto");
            }
        }
    }//GEN-LAST:event_jTextFieldVentas_CodigoKeyPressed

    private void jTextFieldVentas_CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVentas_CodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVentas_CodigoActionPerformed

    private void jTextFieldVenta_CantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldVenta_CantidadKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!"".equals(jTextFieldVenta_Cantidad.getText())) {
                int Codigo = Integer.parseInt(jTextFieldVentas_Codigo.getText());
                String Descripcion = jTextFieldVentas_Nombre.getText();
                int Cantidad = Integer.parseInt(jTextFieldVenta_Cantidad.getText());
                double IVA = p.getIVA();
                double V_Unitario = Double.parseDouble(jTextFieldVentas_Precio.getText());
                double V_Total = (V_Unitario + (V_Unitario*IVA))*Cantidad;
                double iva_total = V_Unitario * Cantidad * IVA;
                int stock = Integer.parseInt(jTextFieldVentas_Stock.getText());
                
                if (stock >= Cantidad) {
                    item = item + 1;
                    modelo = (DefaultTableModel) jTableVentas.getModel();
                    for (int i = 0; i < jTableVentas.getRowCount(); i++) {
                        if (jTableVentas.getValueAt(i, 1).equals(jTextFieldVentas_Nombre.getText())) {
                            JOptionPane.showMessageDialog(null, "El producto ya esta registrado");
                            return;
                        }
                    }
                    ArrayList lista = new ArrayList();
                    lista.add(item);
                    lista.add(Codigo);
                    lista.add(Descripcion);
                    lista.add(Cantidad);
                    lista.add(V_Unitario);
                    lista.add(iva_total);
                    lista.add(V_Total);
                    Object[] Ob = new Object[6];
                    Ob[0] = lista.get(1);
                    Ob[1] = lista.get(2);
                    Ob[2] = lista.get(3);
                    Ob[3] = lista.get(4);
                    Ob[4] = lista.get(5);
                    Ob[5] = lista.get(6);
                    modelo.addRow(Ob);
                    jTableVentas.setModel(modelo);
                    TotalPagar();
                    LimpiarVenta();
                    jTextFieldVentas_Codigo.requestFocus();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Stock no disponible");
                }
            }else
            {
            JOptionPane.showMessageDialog(null, "Ingrese la cantidad");
            }
        }
        
    }//GEN-LAST:event_jTextFieldVenta_CantidadKeyPressed

    private void jButtonEliminar_VentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminar_VentaActionPerformed
        // TODO add your handling code here:
        modelo = (DefaultTableModel) jTableVentas.getModel();
        modelo.removeRow(jTableVentas.getSelectedRow());
        TotalPagar();
        jTextFieldVentas_Codigo.requestFocus();
    }//GEN-LAST:event_jButtonEliminar_VentaActionPerformed

    private void jButtonRegistrar_VentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrar_VentaActionPerformed
        // TODO add your handling code here:
        RegistrarVenta();
        ActualizarStock();
        modelo = (DefaultTableModel) jTableVentas.getModel();
        for (int i = 0; i <= jTableVentas.getRowCount() + 1 ; i++) {
            modelo.removeRow(0);
        }
        TotalPagar();
        LimpiarVenta();
    }//GEN-LAST:event_jButtonRegistrar_VentaActionPerformed

    private void jTextFieldCodigo_PedidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigo_PedidosKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!"".equals(jTextFieldCodigo_Pedidos.getText())) {
                int Cod = Integer.parseInt(jTextFieldCodigo_Pedidos.getText());
                p = product.BuscarProductos(Cod);
                if (p.getNombre() != null) {
                    jTextFieldDescripcion_Pedido.setText(""+p.getNombre());
                    jTextFieldCantidad_Pedido.requestFocus();
                }
                else{
                    jTextFieldDescripcion_Pedido.setText("");
                    jTextFieldCodigo_Pedidos.requestFocus();
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Ingrese el codigo del producto");
            }
        }
    }//GEN-LAST:event_jTextFieldCodigo_PedidosKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ActualizarStockPedido();
        LimpiarTabla();
        ListarProductoPedidos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "La ganancia total es de: " + ganancia_Total);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonPromedio_VentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPromedio_VentasActionPerformed
        // TODO add your handling code here:
        double promedio = 0.00;
        int cantidadVendida = 0;
        for (int i = 0; i < jTableVentas_Estadisticas.getRowCount(); i++) {
            int cantidad = Integer.parseInt(jTableVentas_Estadisticas.getValueAt(i, 2).toString());
            cantidadVendida = cantidadVendida + cantidad;
        }
        promedio = ganancia_Total/cantidadVendida;
        JOptionPane.showMessageDialog(null, "El promedio de ventas es de: " + promedio);
    }//GEN-LAST:event_jButtonPromedio_VentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Estadisticas_button;
    private javax.swing.JButton Pedidos_button;
    private javax.swing.JButton Productos_button;
    private javax.swing.JButton Realizar_Venta_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonEliminar_Venta;
    private javax.swing.JButton jButtonPromedio_Ventas;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JButton jButtonRegistrar_Venta;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelCodigo_Pedidos;
    private javax.swing.JLabel jLabelHeader;
    private javax.swing.JLabel jLabelMinimo;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelTotal_Pago;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelNavbar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTablePedidos;
    private javax.swing.JTable jTableProducto;
    private javax.swing.JTable jTableVentas;
    private javax.swing.JTable jTableVentas_Estadisticas;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldCantidad_Pedido;
    private javax.swing.JTextField jTextFieldCodigo_Pedidos;
    private javax.swing.JTextField jTextFieldDescripcion_Pedido;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldMinimo;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldVenta_Cantidad;
    private javax.swing.JTextField jTextFieldVentas_Codigo;
    private javax.swing.JTextField jTextFieldVentas_Nombre;
    private javax.swing.JTextField jTextFieldVentas_Precio;
    private javax.swing.JTextField jTextFieldVentas_Stock;
    private javax.swing.JTextField jTextFieldVentas_Tipo;
    // End of variables declaration//GEN-END:variables
    private void TotalPagar()
    {
        TotalPagar = 0.00;
        int numfila = jTableVentas.getRowCount();
        for (int i = 0; i < numfila; i++) {
            double cal = Double.parseDouble(String.valueOf(jTableVentas.getModel().getValueAt(i, 5)));
            TotalPagar = TotalPagar + cal;
        }
        jLabelTotal_Pago.setText(String.format("%.2f", TotalPagar));
    }
    
    private void LimpiarVenta()
    {
        jTextFieldVentas_Codigo.setText("");
        jTextFieldVentas_Tipo.setText("");
        jTextFieldVentas_Nombre.setText("");
        jTextFieldVentas_Precio.setText("");
        jTextFieldVenta_Cantidad.setText("");
        jTextFieldVentas_Stock.setText("");
    }
    
    private void LimpiarProducto()
    {
        jTextFieldID.setText("");
        jTextFieldNombre.setText("");
        jTextFieldPrecio.setText("");
        jTextFieldCantidad.setText("");
        jTextFieldMinimo.setText("");
    }
    
    private void RegistrarVenta()
    {
        for (int i = 0; i < jTableVentas.getRowCount(); i++) {
            int codigo = Integer.parseInt(jTableVentas.getValueAt(i, 0).toString());
            String descripcion = jTableVentas.getValueAt(i, 1).toString();
            int cantidad = Integer.parseInt(jTableVentas.getValueAt(i, 2).toString());
            double v_unitario = Double.parseDouble(jTableVentas.getValueAt(i, 3).toString());
            double IVA = Double.parseDouble(jTableVentas.getValueAt(i, 4).toString());
            double v_total = Double.parseDouble(jTableVentas.getValueAt(i, 5).toString());
            v.setCodigo(codigo);
            v.setDescripcion(descripcion);
            v.setCantidad(cantidad);
            v.setV_Unitario(v_unitario);
            v.setIVA(IVA);
            v.setV_Total(v_total);
            vent.RegistrarVenta(v);
        }
    }
    
    private void ActualizarStock()
    {
        for (int i = 0; i < jTableVentas.getRowCount(); i++) {
            int codigo = Integer.parseInt(jTableVentas.getValueAt(i, 0).toString());
            int cantidad = Integer.parseInt(jTableVentas.getValueAt(i, 2).toString());
            p = product.BuscarProductos(codigo);
            int stockActual = p.getCantidadBodega() - cantidad;
            product.ActualizarStock(stockActual, codigo);
        }
    }
    
    private void EsNecesarioHacerPedido()
    {
        for (int i = 0; i < jTablePedidos.getRowCount(); i++) {
            int Stock = Integer.parseInt(jTablePedidos.getValueAt(i, 3).toString());
            int StockMinimo = Integer.parseInt(jTablePedidos.getValueAt(i, 4).toString());
            if (Stock < StockMinimo) {
                JOptionPane.showMessageDialog(null, "Debe realizar pedido de " + jTablePedidos.getValueAt(i, 2).toString());
            }
        }

    }
    
    private void ActualizarStockPedido()
    {
            int codigo = Integer.parseInt(jTextFieldCodigo_Pedidos.getText());
            int cantidad = Integer.parseInt(jTextFieldCantidad_Pedido.getText());
            p = product.BuscarProductos(codigo);
            int stockActual = p.getCantidadBodega() + cantidad;
            product.ActualizarStock(stockActual, codigo);
    }
    
    private void GananciaTotal()
    {
        ganancia_Total = 0.00;
        for (int i = 0; i < jTableVentas_Estadisticas.getRowCount(); i++) {
            int cantidad = Integer.parseInt(jTableVentas_Estadisticas.getValueAt(i, 2).toString());
            double v_unitario = Double.parseDouble(jTableVentas_Estadisticas.getValueAt(i, 3).toString());
            double ganancia = v_unitario * cantidad;
            ganancia_Total = ganancia_Total + ganancia;
        }
    }
}
